baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

  [[menus.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 20

  [[menus.main]]
  name = 'Tags'
  pageRef = '/tags'
  weight = 30


[taxonomies]
    series = 'series'
    tags = 'tags'


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[mediaTypes]
    [mediaTypes."application/feed+json"]
    suffixes = ["json"]

[outputFormats.jsonfeed]
  mediaType = "application/feed+json"
  baseName = "feed"
  rel = "alternate"
  isPlainText = true

[outputs]
  home = ["HTML", "RSS", "JSON", "jsonfeed"]
  section = ["HTML", "RSS", "jsonfeed"]
  page = ["HTML"]

